name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to 'master' if your default branch is 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Copy the index.html and assets to a temporary folder
      - name: Copy files to deploy folder
        run: |
          mkdir -p ./deploy
          cp -r src/main/resources/static/FronEnd/HTML_Files/* ./deploy/

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy/
